---
title: "Berg Monthly Spending"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
    html_document:
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE,warning=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(shiny)
library(DT)
library(plotly)
library(lubridate)
source(file.path('helperFunctions.R', fsep = .Platform$file.sep))

#read in all transactions from mint
all_transactions <- readInTransactions("transactions.csv")

desc_cat_uniq <- unique(all_transactions$transaction_cat)

getAllUniqueDebitTrans <- function(acct){
    df <- all_transactions %>% 
        filter(account_name %in% c(acct),transaction_type %in% c("debit")) %>% 
        distinct(posting_date,description,transaction_cat, .keep_all = TRUE)
    return(df)
}
#create sub dataframes by account name
SLFCU_CHECK_trans <- getAllUniqueDebitTrans("S/D - Money Manager")
SLFCU_SAV_trans <- getAllUniqueDebitTrans("Regular Share")
WF_VISA_trans <- getAllUniqueDebitTrans("WELLS FARGO CASH BACK VISA SIGNATURE CARD")
WF_SAV_trans <- getAllUniqueDebitTrans("WAY2SAVE® SAVINGS")
WF_CHECK_trans <- getAllUniqueDebitTrans("CUSTOM MANAGEMENT(RM)")
NOV_CHECK_trans <- getAllUniqueDebitTrans("INCENTIVE CHECKING")
NOV_MORT_trans <- getAllUniqueDebitTrans("30 Year Mortgage")
CARPAY_trans <- getAllUniqueDebitTrans("SUBARU ACCOUNT")
```

# Monthly Bills
```{r echo=FALSE, fig.width=12}
df = getTransactionsByMonthByDescription(all_df = SLFCU_CHECK_trans,
                                         minDate = mdy("06/01/2018"),
                                         maxDate = mdy(format(Sys.time(), '%B %d, %Y')),
                                         descriptions = c("Xcel Energy","City of Woodbury","Comcast","Tennis Sanitation","Subaru Car Payment","Mortgage Transfer to Novation"),
                                         minAmount = 0,
                                         maxAmount = 10000)
p <- plotMonthlyTransactionSummaryByDescriptionsStacked(df)
p
```

# Groceries

## Main Stores
```{r echo=FALSE, fig.width=12}
df = getTransactionsByMonthByDescription(all_df = SLFCU_CHECK_trans,
                                         minDate = mdy("06/01/2018"),
                                         maxDate = mdy("01/30/2019"),
                                         # descriptions = c("Hy-Vee","Trader Joe's","Costco","Kowalski's"),
                                          descriptions = c("Hy-Vee","Trader Joe's","Costco"),
                                         minAmount = 0,
                                         maxAmount = 10000) %>% arrange(desc(amount))
p <- plotMonthlyTransactionSummaryByDescriptionsStacked(df)
p
```

## Others

```{r echo=FALSE, fig.width=12}
SLFCU_CHECK_trans_filtered <- SLFCU_CHECK_trans %>% filter(!description %in%  c("Hy-Vee","Trader Joe's","Costco"))
df = getTransactionsByMonthByDescription(all_df = SLFCU_CHECK_trans_filtered,
                                         minDate = mdy("06/01/2018"),
                                         maxDate = mdy("01/30/2019"),
                                         descriptions = c("Groceries"),
                                         minAmount = 0,
                                         maxAmount = 10000)
p <- plotMonthlyTransactionSummaryByDescriptionsStacked(df)
p
```

# Restaurants

## Main Ones
```{r echo=FALSE, fig.width=12}
df = getTransactionsByMonthByDescription(all_df = SLFCU_CHECK_trans,
                                         minDate = mdy("06/01/2018"),
                                         maxDate = mdy("01/30/2019"),
                                         descriptions = c("Domino's Pizza","KFC","Roccos Pizza","Subway","Super 99 Buffet","Taco Bell","Chick-Fil-A"),
                                         minAmount = 0,
                                         maxAmount = 10000) %>% arrange(desc(amount))
p <- plotMonthlyTransactionSummaryByDescriptionsStacked(df)
p
```

## Others

```{r echo=FALSE, fig.width=12}
SLFCU_CHECK_trans_filtered <- SLFCU_CHECK_trans %>% filter(!description %in%  c("Domino's Pizza","KFC","Roccos Pizza","Subway","Super 99 Buffet","Taco Bell","Chick-Fil-A"))
df = getTransactionsByMonthByDescription(all_df = SLFCU_CHECK_trans_filtered,
                                         minDate = mdy("06/01/2018"),
                                         maxDate = mdy("01/30/2019"),
                                         descriptions = c("Restaurants"),
                                         minAmount = 0,
                                         maxAmount = 10000) %>% arrange(desc(amount))
p <- plotMonthlyTransactionSummaryByDescriptionsStacked(df)
p
```

# Entertainment
```{r echo=FALSE, fig.width=12}
df = getTransactionsByMonthByDescription(all_df = SLFCU_CHECK_trans,
                                         minDate = mdy("06/01/2018"),
                                         maxDate = mdy("01/30/2019"),
                                         descriptions = c("Entertainment"),
                                         minAmount = 0,
                                         maxAmount = 10000) %>% arrange(desc(amount))
p <- plotMonthlyTransactionSummaryByDescriptions(df)
p
```